//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhocGiftShop.Models.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductFormat()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int idPF { get; set; }
        public int idPro { get; set; }
        public string size { get; set; }
        public Nullable<int> price { get; set; }
        public string colorCSS { get; set; }
        public string colorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
    }
}
